Repository prgrms-be-devcourse/BE-04-TICKETPARIS, pull requests merged in 2023-09, with the labels that each got.

#6 [#5] CI 환경 구축
  .github/workflows/ci.yml
  Dockerfile
  src/main/resources/application-prod.yml
  src/test/java/com/programmers/ticketparis/TicketparisApplicationTests.java
Labels: dev-빌드, op-기타

#10 [#8] CD 환경 구축
  .github/workflows/cd-dev-with-docker-compose.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  deploy/docker-compose.yml
Labels: dev-빌드, op-기타

#11 [#9] RestControllerAdvice를 이용한 전역 예외 처리 설정
  src/main/java/com/programmers/ticketparis/common/dto/ErrorResponse.java
  src/main/java/com/programmers/ticketparis/common/exception/BusinessException.java
  src/main/java/com/programmers/ticketparis/common/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/common/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: dev-신규 기능

#20 [#19] 도메인 생성
  src/main/java/com/programmers/ticketparis/domain/member/Customer.java
  src/main/java/com/programmers/ticketparis/domain/member/Seller.java
  src/main/java/com/programmers/ticketparis/domain/performance/Category.java
  src/main/java/com/programmers/ticketparis/domain/performance/Hall.java
  src/main/java/com/programmers/ticketparis/domain/performance/Performance.java
  src/main/java/com/programmers/ticketparis/domain/reservation/Reservation.java
  src/main/java/com/programmers/ticketparis/domain/reservation/ReservationStatus.java
  src/main/java/com/programmers/ticketparis/domain/schedule/Schedule.java
Labels: dev-신규 기능

#23 [#21] CI 작업 기록 삭제 조치
  .github/workflows/ci.yml
Labels: dev-버그, dev-빌드

#26 [#25] 패키지 구조 변경 (common 패키지 삭제)
  src/main/java/com/programmers/ticketparis/dto/ErrorResponse.java
  src/main/java/com/programmers/ticketparis/exception/BusinessException.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/GlobalExceptionHandler.java
Labels: dev-리팩토링

#27 [#22] 테스팅 용 DDL, DML을 통한 더미 데이터 삽입
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: dev-기타

#30 [#28] 스케줄 기능 개발
  src/main/java/com/programmers/ticketparis/controller/schedule/ScheduleController.java
  src/main/java/com/programmers/ticketparis/dto/ApiResponse.java
  src/main/java/com/programmers/ticketparis/dto/schedule/request/ScheduleCreateRequest.java
  src/main/java/com/programmers/ticketparis/dto/schedule/response/ScheduleResponse.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/ticketparis/exception/ScheduleException.java
  src/main/java/com/programmers/ticketparis/repository/schedule/MybatisScheduleRepository.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleMapper.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleRepository.java
  src/main/java/com/programmers/ticketparis/service/schedule/ScheduleService.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/programmers/ticketparis/repository/schedule/MybatisScheduleRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/schedule/ScheduleServiceTest.java
Labels: dev-신규 기능, dev-테스트

#29 [#14] 예매 기능 개발
  src/main/java/com/programmers/ticketparis/controller/reservation/ReservationController.java
  src/main/java/com/programmers/ticketparis/domain/reservation/Reservation.java
  src/main/java/com/programmers/ticketparis/domain/reservation/ReservationStatus.java
  src/main/java/com/programmers/ticketparis/dto/reservation/request/ReservationCreateRequest.java
  src/main/java/com/programmers/ticketparis/dto/reservation/response/ReservationResponse.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/ReservationException.java
  src/main/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepository.java
  src/main/java/com/programmers/ticketparis/repository/reservation/ReservationMapper.java
  src/main/java/com/programmers/ticketparis/repository/reservation/ReservationRepository.java
  src/main/java/com/programmers/ticketparis/service/reservation/ReservationService.java
  src/main/resources/mapper/ReservationMapper.xml
  src/test/java/com/programmers/ticketparis/domain/reservation/ReservationTest.java
  src/test/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/reservation/ReservationServiceTest.java
  src/test/resources/application.yml
Labels: dev-신규 기능

#24 [#4]구매자 CRUD 개발
  src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
  src/main/java/com/programmers/ticketparis/domain/member/Customer.java
  src/main/java/com/programmers/ticketparis/domain/member/Seller.java
  src/main/java/com/programmers/ticketparis/domain/performance/Performance.java
  src/main/java/com/programmers/ticketparis/dto/ApiResponse.java
  src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
  src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/EmailValid.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/EmailValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PasswordValid.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PasswordValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PhoneValid.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PhoneValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/UsernameValid.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/UsernameValidator.java
  src/main/java/com/programmers/ticketparis/exception/CustomerException.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/mapper/member/CustomerMapper.java
  src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
  src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
  src/main/java/com/programmers/ticketparis/service/member/CustomerService.java
  src/main/resources/mapper/CustomerMapper.xml
  src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/member/CustomerServiceTest.java
Labels: dev-신규 기능, dev-테스트

#47 [#40] Redis 서버 환경 구축
  .github/workflows/cd-dev-with-docker-compose.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/programmers/ticketparis/redis/RedisConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: dev-신규 기능

#13 [#7] 공연 CRUD 및 테스트 코드 작성(MVP 기능 + 모든 CRUD 기능 구현)
  build.gradle
  src/main/java/com/programmers/ticketparis/controller/performance/PerformanceController.java
  src/main/java/com/programmers/ticketparis/domain/performance/Category.java
  src/main/java/com/programmers/ticketparis/domain/performance/CategoryEnumTypeHandler.java
  src/main/java/com/programmers/ticketparis/domain/performance/Performance.java
  src/main/java/com/programmers/ticketparis/dto/ErrorResponse.java
  src/main/java/com/programmers/ticketparis/dto/performance/ApiResponse.java
  src/main/java/com/programmers/ticketparis/dto/performance/request/PerformanceCreateRequest.java
  src/main/java/com/programmers/ticketparis/dto/performance/request/PerformanceUpdateRequest.java
  src/main/java/com/programmers/ticketparis/dto/performance/response/PerformanceIdResponse.java
  src/main/java/com/programmers/ticketparis/dto/performance/response/PerformanceResponse.java
  src/main/java/com/programmers/ticketparis/exception/BusinessException.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/ticketparis/exception/PerformanceException.java
  src/main/java/com/programmers/ticketparis/mapper/PerformanceMapper.java
  src/main/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepository.java
  src/main/java/com/programmers/ticketparis/repository/performance/PerformanceRepository.java
  src/main/java/com/programmers/ticketparis/service/performance/PerformanceService.java
  src/main/resources/application.yml
  src/main/resources/mapper/PerformanceMapper.xml
  src/test/java/com/programmers/ticketparis/domain/performance/PerformanceTest.java
  src/test/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/performance/PerformanceServiceTest.java
  src/test/resources/application.yml
Labels: dev-신규 기능, dev-테스트

#50 [#35] (인증, 인가) 비밀번호 암호화 기능 구현
  build.gradle
  src/main/java/com/programmers/ticketparis/domain/member/Customer.java
  src/test/java/com/programmers/ticketparis/domain/member/CustomerTest.java
  src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
Labels: dev-신규 기능, dev-테스트

#56 [#55} 비밀번호 암호화 테스트 수정
  src/test/java/com/programmers/ticketparis/domain/member/CustomerTest.java
Labels: dev-버그

#59 [#58] ApiResponse 중복 파일 삭제
  src/main/java/com/programmers/ticketparis/controller/performance/PerformanceController.java
  src/main/java/com/programmers/ticketparis/domain/performance/Category.java
  src/main/java/com/programmers/ticketparis/domain/performance/CategoryEnumTypeHandler.java
  src/main/java/com/programmers/ticketparis/domain/performance/Performance.java
  src/main/java/com/programmers/ticketparis/dto/ErrorResponse.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/EmailValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PasswordValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/PhoneValidator.java
  src/main/java/com/programmers/ticketparis/dto/member/validator/UsernameValidator.java
  src/main/java/com/programmers/ticketparis/dto/performance/ApiResponse.java
  src/main/java/com/programmers/ticketparis/dto/performance/request/PerformanceCreateRequest.java
  src/main/java/com/programmers/ticketparis/dto/performance/request/PerformanceUpdateRequest.java
  src/main/java/com/programmers/ticketparis/dto/performance/response/PerformanceIdResponse.java
  src/main/java/com/programmers/ticketparis/dto/performance/response/PerformanceResponse.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepository.java
Labels: dev-버그

#38 [#37] 예매시 스케줄 좌석 수 변경 관련 기능
  src/main/java/com/programmers/ticketparis/domain/reservation/Reservation.java
  src/main/java/com/programmers/ticketparis/domain/schedule/Schedule.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/repository/schedule/MybatisScheduleRepository.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleMapper.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleRepository.java
  src/main/java/com/programmers/ticketparis/service/reservation/ReservationService.java
  src/main/java/com/programmers/ticketparis/service/schedule/ScheduleService.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/programmers/ticketparis/domain/reservation/ReservationTest.java
  src/test/java/com/programmers/ticketparis/service/schedule/ScheduleServiceTest.java
Labels: dev-신규 기능, dev-리팩토링

#57 [#54] 단순 전체 랭킹 조회 기능
  src/main/java/com/programmers/ticketparis/controller/ranking/RankingController.java
  src/main/java/com/programmers/ticketparis/dto/ranking/response/RankingResponse.java
  src/main/java/com/programmers/ticketparis/repository/ranking/MybatisRankingRepository.java
  src/main/java/com/programmers/ticketparis/repository/ranking/RankingMapper.java
  src/main/java/com/programmers/ticketparis/repository/ranking/RankingRepository.java
  src/main/java/com/programmers/ticketparis/service/ranking/RankingService.java
  src/main/resources/application.yml
  src/main/resources/mapper/RankingMapper.xml
  src/test/resources/application.yml
Labels: dev-신규 기능

#43 [#31] ResponseBodyAdvice를 이용한 응답 형식 통일, 에러 로그 형식 변경
  src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
  src/main/java/com/programmers/ticketparis/controller/member/SellerController.java
  src/main/java/com/programmers/ticketparis/controller/performance/PerformanceController.java
  src/main/java/com/programmers/ticketparis/controller/ranking/RankingController.java
  src/main/java/com/programmers/ticketparis/controller/reservation/ReservationController.java
  src/main/java/com/programmers/ticketparis/controller/schedule/ScheduleController.java
  src/main/java/com/programmers/ticketparis/domain/performance/Performance.java
  src/main/java/com/programmers/ticketparis/domain/reservation/Reservation.java
  src/main/java/com/programmers/ticketparis/dto/ApiResponse.java
  src/main/java/com/programmers/ticketparis/dto/ErrorData.java
  src/main/java/com/programmers/ticketparis/dto/ErrorResponse.java
  src/main/java/com/programmers/ticketparis/dto/ResponseWrapper.java
  src/main/java/com/programmers/ticketparis/dto/reservation/response/ReservationIdResponse.java
  src/main/java/com/programmers/ticketparis/exception/BusinessException.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/ticketparis/exception/ReservationException.java
  src/main/java/com/programmers/ticketparis/exception/ScheduleException.java
  src/main/java/com/programmers/ticketparis/service/performance/PerformanceService.java
  src/main/java/com/programmers/ticketparis/service/reservation/ReservationService.java
  src/test/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepositoryTest.java
  src/test/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/performance/PerformanceServiceTest.java
  src/test/java/com/programmers/ticketparis/service/reservation/ReservationServiceTest.java
Labels: dev-리팩토링

#48 [#39] 공연, 예매, 스케줄 페이지네이션 기능 적용
  src/main/java/com/programmers/ticketparis/common/pageable/Pageable.java
  src/main/java/com/programmers/ticketparis/controller/performance/PerformanceController.java
  src/main/java/com/programmers/ticketparis/controller/reservation/ReservationController.java
  src/main/java/com/programmers/ticketparis/controller/schedule/ScheduleController.java
  src/main/java/com/programmers/ticketparis/dto/schedule/response/ScheduleIdResponse.java
  src/main/java/com/programmers/ticketparis/dto/schedule/response/ScheduleResponse.java
  src/main/java/com/programmers/ticketparis/exception/CommonException.java
  src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/repository/member/CustomerMapper.java
  src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
  src/main/java/com/programmers/ticketparis/repository/member/MyBatisSellerRepository.java
  src/main/java/com/programmers/ticketparis/repository/member/SellerMapper.java
  src/main/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepository.java
  src/main/java/com/programmers/ticketparis/repository/performance/PerformanceMapper.java
  src/main/java/com/programmers/ticketparis/repository/performance/PerformanceRepository.java
  src/main/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepository.java
  src/main/java/com/programmers/ticketparis/repository/reservation/ReservationMapper.java
  src/main/java/com/programmers/ticketparis/repository/reservation/ReservationRepository.java
  src/main/java/com/programmers/ticketparis/repository/schedule/MybatisScheduleRepository.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleMapper.java
  src/main/java/com/programmers/ticketparis/repository/schedule/ScheduleRepository.java
  src/main/java/com/programmers/ticketparis/service/performance/PerformanceService.java
  src/main/java/com/programmers/ticketparis/service/reservation/ReservationService.java
  src/main/java/com/programmers/ticketparis/service/schedule/ScheduleService.java
  src/main/resources/mapper/CustomerMapper.xml
  src/main/resources/mapper/PerformanceMapper.xml
  src/main/resources/mapper/ReservationMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/resources/mapper/SellerMapper.xml
  src/test/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepositoryTest.java
  src/test/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepositoryTest.java
  src/test/java/com/programmers/ticketparis/service/performance/PerformanceServiceTest.java
Labels: dev-신규 기능

#67 [#66] Local DB H2 -> MySQL 변경 작업
  src/main/resources/application-local.yml
  src/test/resources/data.sql
  src/test/resources/schema.sql
Labels: dev-빌드

#69 [#68] MyBatis Id값 반환 관련 이슈 해결
  src/main/java/com/programmers/ticketparis/repository/performance/MybatisPerformanceRepository.java
  src/main/java/com/programmers/ticketparis/repository/performance/PerformanceMapper.java
  src/main/java/com/programmers/ticketparis/repository/reservation/MybatisReservationRepository.java
  src/main/java/com/programmers/ticketparis/repository/reservation/ReservationMapper.java
Labels: dev-버그

#65 [#60] 사용자 인증 기능 구현 - 1
  src/main/java/com/programmers/ticketparis/common/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/member/controller/CustomerController.java
  src/main/java/com/programmers/ticketparis/member/domain/Customer.java
  src/main/java/com/programmers/ticketparis/member/dto/CustomerLoginForm.java
  src/main/java/com/programmers/ticketparis/member/dto/request/CustomerCreateRequest.java
  src/main/java/com/programmers/ticketparis/member/dto/request/SellerCreateRequest.java
  src/main/java/com/programmers/ticketparis/member/dto/response/LoginResponse.java
  src/main/java/com/programmers/ticketparis/member/repository/CustomerRepository.java
  src/main/java/com/programmers/ticketparis/member/repository/mapper/CustomerMapper.java
  src/main/java/com/programmers/ticketparis/member/repository/mybatis/MybatisCustomerRepository.java
  src/main/java/com/programmers/ticketparis/member/service/CustomerService.java
  src/main/resources/mapper/CustomerMapper.xml
Labels: dev-신규 기능, dev-테스트

#78 [#61] 공연 예매, 예매 취소에 대한 비관적 락 적용
  src/main/java/com/programmers/ticketparis/common/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/reservation/service/ReservationService.java
  src/main/java/com/programmers/ticketparis/schedule/repository/ScheduleRepository.java
  src/main/java/com/programmers/ticketparis/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/programmers/ticketparis/schedule/repository/mybatis/MybatisScheduleRepository.java
  src/main/java/com/programmers/ticketparis/schedule/service/ScheduleService.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/programmers/ticketparis/reservation/service/ReservationPessimisticTest.java
  src/test/java/com/programmers/ticketparis/reservation/service/ReservationServiceTest.java
Labels: dev-신규 기능

#74 Reservation(예매) RestAssured 테스트 + Swagger 적용
  build.gradle
  src/main/java/com/programmers/ticketparis/config/SwaggerConfig.java
  src/main/java/com/programmers/ticketparis/reservation/controller/ReservationController.java
  src/test/java/com/programmers/ticketparis/reservation/controller/ReservationControllerTest.java
Labels: dev-테스트

#77 Schedule Rest Assured 테스트 적용 + Swagger 적용
  src/main/java/com/programmers/ticketparis/schedule/controller/ScheduleController.java
  src/main/java/com/programmers/ticketparis/schedule/dto/request/ScheduleCreateRequest.java
  src/test/java/com/programmers/ticketparis/schedule/controller/ScheduleControllerTest.java
Labels: dev-테스트

#82 Performance Rest Assured 테스트 적용 + Swagger 적용
  src/main/java/com/programmers/ticketparis/performance/controller/PerformanceController.java
  src/main/java/com/programmers/ticketparis/performance/dto/request/PerformanceCreateRequest.java
  src/test/java/com/programmers/ticketparis/performance/controller/PerformanceControllerTest.java
  src/test/java/com/programmers/ticketparis/performance/service/PerformanceServiceTest.java
Labels: dev-테스트

#84 [#81] CI Jacoco 적용
  .github/workflows/ci.yml
  build.gradle
Labels: dev-빌드, op-기타

#88 chore: Swagger Config 폴더 변경
  src/main/java/com/programmers/ticketparis/common/config/SwaggerConfig.java
Labels: dev-리팩토링

#75 [#62] 단순 랭킹 조회 시 캐시 적용
  src/main/java/com/programmers/ticketparis/TicketparisApplication.java
  src/main/java/com/programmers/ticketparis/common/config/RedisConfig.java
  src/main/java/com/programmers/ticketparis/common/config/SwaggerConfig.java
  src/main/java/com/programmers/ticketparis/member/dto/CustomerLoginForm.java
  src/main/java/com/programmers/ticketparis/performance/controller/PerformanceController.java
  src/main/java/com/programmers/ticketparis/performance/dto/request/PerformanceCreateRequest.java
  src/main/java/com/programmers/ticketparis/ranking/controller/RankingController.java
  src/main/java/com/programmers/ticketparis/ranking/dto/response/RankingResponse.java
  src/main/java/com/programmers/ticketparis/ranking/service/RankingScheduler.java
  src/main/java/com/programmers/ticketparis/ranking/service/RankingService.java
  src/main/java/com/programmers/ticketparis/ranking/service/RedisRankingService.java
  src/main/java/com/programmers/ticketparis/reservation/controller/ReservationController.java
  src/main/java/com/programmers/ticketparis/schedule/controller/ScheduleController.java
  src/main/java/com/programmers/ticketparis/schedule/dto/request/ScheduleCreateRequest.java
  src/main/resources/mapper/RankingMapper.xml
Labels: dev-신규 기능

#93 [#86] Redisson을 이용한 분산 락 적용(비관적 락 개선)
  build.gradle
  src/main/java/com/programmers/ticketparis/common/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/reservation/controller/ReservationController.java
  src/main/java/com/programmers/ticketparis/reservation/service/ReservationRedissonFacade.java
  src/main/java/com/programmers/ticketparis/reservation/service/ReservationService.java
  src/main/resources/application-local.yml
  src/test/java/com/programmers/ticketparis/reservation/service/ReservationPessimisticTest.java
Labels: dev-빌드, op-기타

#98 [#97] Elastic Cache 배포시 테스트 환경 변경
  .github/workflows/cd-dev-with-docker-compose.yml
  .github/workflows/ci.yml
Labels: dev-버그

#101 [#100] Local, Dev 환경에 따른 RedisConfig 설정 변경
  src/main/java/com/programmers/ticketparis/common/config/RedisConfig.java
Labels: dev-버그

#103 [#102] CD 단계에서 패스워드 분리
  .github/workflows/cd-dev-with-docker-compose.yml
  .github/workflows/ci.yml
  src/main/java/com/programmers/ticketparis/common/config/RedisConfig.java
  src/main/java/com/programmers/ticketparis/ranking/controller/RankingController.java
Labels: dev-버그

#105 [#104] docker compose 명령어 오터 수정
  .github/workflows/cd-dev-with-docker-compose.yml
Labels: dev-버그

#90 [#73] 사용자 인증 기능 구현 - 2
  src/main/java/com/programmers/ticketparis/auth/controller/AuthController.java
  src/main/java/com/programmers/ticketparis/auth/dto/LoginRequest.java
  src/main/java/com/programmers/ticketparis/auth/dto/LoginSuccessResponse.java
  src/main/java/com/programmers/ticketparis/auth/dto/LogoutSuccessResponse.java
  src/main/java/com/programmers/ticketparis/auth/dto/SessionValueDto.java
  src/main/java/com/programmers/ticketparis/auth/exception/AuthException.java
  src/main/java/com/programmers/ticketparis/auth/mvc/filter/AuthenticationFilter.java
  src/main/java/com/programmers/ticketparis/auth/mvc/filter/ExceptionHandlerFilter.java
  src/main/java/com/programmers/ticketparis/auth/repository/SessionRepository.java
  src/main/java/com/programmers/ticketparis/auth/repository/localCashSessionRepository.java
  src/main/java/com/programmers/ticketparis/auth/service/AuthService.java
  src/main/java/com/programmers/ticketparis/common/config/AuthConfig.java
  src/main/java/com/programmers/ticketparis/common/exception/BusinessException.java
  src/main/java/com/programmers/ticketparis/common/exception/ExceptionRule.java
  src/main/java/com/programmers/ticketparis/common/util/SessionConst.java
  src/main/java/com/programmers/ticketparis/member/controller/CustomerController.java
  src/main/java/com/programmers/ticketparis/member/domain/Customer.java
  src/main/java/com/programmers/ticketparis/member/domain/Seller.java
  src/main/java/com/programmers/ticketparis/member/dto/response/LoginResponse.java
  src/main/java/com/programmers/ticketparis/member/enums/MemberRule.java
  src/main/java/com/programmers/ticketparis/member/exception/CustomerException.java
  src/main/java/com/programmers/ticketparis/member/exception/SellerException.java
  src/main/java/com/programmers/ticketparis/member/repository/SellerRepository.java
  src/main/java/com/programmers/ticketparis/member/repository/mapper/SellerMapper.java
  src/main/java/com/programmers/ticketparis/member/repository/mybatis/MybatisSellerRepository.java
  src/main/java/com/programmers/ticketparis/member/service/CustomerService.java
  src/main/java/com/programmers/ticketparis/member/service/SellerService.java
  src/main/resources/mapper/SellerMapper.xml
  src/test/java/com/programmers/ticketparis/performance/controller/PerformanceControllerTest.java
  src/test/java/com/programmers/ticketparis/reservation/controller/ReservationControllerTest.java
  src/test/java/com/programmers/ticketparis/schedule/controller/ScheduleControllerTest.java
  src/test/resources/data.sql
Labels: dev-신규 기능

#109 SonarQube GitAction 및 PR 코멘트 연동/#108
  .github/workflows/ci.yml
  build.gradle
Labels: dev-테스트

#114 SonarCloud + GitAction 연동 작업 /#111
  .github/workflows/ci.yml
  build.gradle
Labels: dev-리팩토링

#112 [#110] lock 타임 아웃 시간 변경 및 예외 처리
  src/main/java/com/programmers/ticketparis/reservation/service/ReservationRedissonFacade.java
Labels: dev-버그

#115 chore: sonarcloud + jacoco 보고서 경로 추가
  build.gradle
Labels: dev-리팩토링

#119 Swagger 리펙토링(도메인 및 Controller 등)/#118
  src/main/java/com/programmers/ticketparis/auth/controller/AuthController.java
  src/main/java/com/programmers/ticketparis/auth/dto/LoginRequest.java
  src/main/java/com/programmers/ticketparis/auth/dto/LoginSuccessResponse.java
  src/main/java/com/programmers/ticketparis/auth/dto/LogoutSuccessResponse.java
  src/main/java/com/programmers/ticketparis/auth/dto/SessionValueDto.java
  src/main/java/com/programmers/ticketparis/auth/mvc/filter/ExceptionHandlerFilter.java
  src/main/java/com/programmers/ticketparis/common/dto/ApiResponse.java
  src/main/java/com/programmers/ticketparis/common/dto/ApiResponseType.java
  src/main/java/com/programmers/ticketparis/common/dto/ResponseWrapper.java
  src/main/java/com/programmers/ticketparis/member/controller/CustomerController.java
  src/main/java/com/programmers/ticketparis/member/controller/SellerController.java
  src/main/java/com/programmers/ticketparis/member/dto/request/CustomerCreateRequest.java
  src/main/java/com/programmers/ticketparis/member/dto/request/SellerCreateRequest.java
  src/main/java/com/programmers/ticketparis/member/dto/response/CustomerIdResponse.java
  src/main/java/com/programmers/ticketparis/member/dto/response/CustomerResponse.java
  src/main/java/com/programmers/ticketparis/member/dto/response/SellerIdResponse.java
  src/main/java/com/programmers/ticketparis/member/dto/response/SellerResponse.java
  src/main/java/com/programmers/ticketparis/performance/controller/PerformanceController.java
  src/main/java/com/programmers/ticketparis/performance/dto/request/PerformanceCreateRequest.java
  src/main/java/com/programmers/ticketparis/performance/dto/request/PerformanceUpdateRequest.java
  src/main/java/com/programmers/ticketparis/performance/dto/response/PerformanceIdResponse.java
  src/main/java/com/programmers/ticketparis/performance/dto/response/PerformanceResponse.java
  src/main/java/com/programmers/ticketparis/ranking/controller/RankingController.java
  src/main/java/com/programmers/ticketparis/ranking/dto/response/RankingResponse.java
  src/main/java/com/programmers/ticketparis/reservation/controller/ReservationController.java
  src/main/java/com/programmers/ticketparis/reservation/dto/request/ReservationCreateRequest.java
  src/main/java/com/programmers/ticketparis/reservation/dto/response/ReservationIdResponse.java
  src/main/java/com/programmers/ticketparis/reservation/dto/response/ReservationResponse.java
  src/main/java/com/programmers/ticketparis/schedule/controller/ScheduleController.java
  src/main/java/com/programmers/ticketparis/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/programmers/ticketparis/schedule/dto/response/ScheduleIdResponse.java
  src/main/java/com/programmers/ticketparis/schedule/dto/response/ScheduleResponse.java
  src/main/resources/application.yml
Labels: dev-리팩토링

#120 [#91] 사용자 인증, 인가 기능 구현 - 3
  src/main/java/com/programmers/ticketparis/auth/dto/Session.java
  src/main/java/com/programmers/ticketparis/auth/dto/SessionValueDto.java
  src/main/java/com/programmers/ticketparis/auth/mvc/filter/AuthenticationFilter.java
  src/main/java/com/programmers/ticketparis/auth/mvc/interceptor/AuthorizationInterceptor.java
  src/main/java/com/programmers/ticketparis/auth/repository/SessionRepository.java
  src/main/java/com/programmers/ticketparis/auth/repository/localCashSessionRepository.java
  src/main/java/com/programmers/ticketparis/auth/service/AuthService.java
  src/main/java/com/programmers/ticketparis/auth/service/SessionExpiryScheduler.java
  src/main/java/com/programmers/ticketparis/auth/util/SessionThreadLocal.java
  src/main/java/com/programmers/ticketparis/auth/util/UrlToMemberRuleMatcher.java
  src/main/java/com/programmers/ticketparis/common/config/AuthConfig.java
  src/main/java/com/programmers/ticketparis/member/enums/MemberRole.java
Labels: dev-신규 기능

#122 [#121] README.md에 프로젝트 관련 내용 추가
  README.md
Labels: dev-문서
